import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../models/warranty_item.dart';
import 'package:intl/intl.dart';

class PDFService {
  Future<Uint8List> generateReport(List<WarrantyItem> items) async {
    final doc = pw.Document();

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return [
            pw.Header(
              level: 0,
              child: pw.Text('ValiDate - Warranty Claim Report', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
            ),
            pw.SizedBox(height: 20),
            // ignore: deprecated_member_use
            pw.Table.fromTextArray(
              context: context,
              data: <List<String>>[
                <String>['Item Name', 'Store', 'Purchase Date', 'Expires', 'Serial #'],
                ...items.map((item) => [
                  item.name,
                  item.storeName,
                  DateFormat('yyyy-MM-dd').format(item.purchaseDate),
                  DateFormat('yyyy-MM-dd').format(item.expiryDate),
                  item.serialNumber,
                ]),
              ],
            ),
            pw.SizedBox(height: 20),
            pw.Text('Generated by ValiDate on ${DateFormat('yyyy-MM-dd HH:mm').format(DateTime.now())}'),
          ];
        },
      ),
    );

    return doc.save();
  }

  Future<void> previewReport(List<WarrantyItem> items) async {
    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => await generateReport(items),
    );
  }
}
